// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHkAOtSes9-9FEfY1mnB4R4VcYu2jAcEY',
    appId: '1:997695311497:web:574908621f4624c8850058',
    messagingSenderId: '997695311497',
    projectId: 'notes-d4f24',
    authDomain: 'notes-d4f24.firebaseapp.com',
    storageBucket: 'notes-d4f24.firebasestorage.app',
    measurementId: 'G-K6XN8JY7K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3AnM52pdl7DtmFN8PKfCGVzpyLxptw84',
    appId: '1:997695311497:android:4a488ac3f0a594ba850058',
    messagingSenderId: '997695311497',
    projectId: 'notes-d4f24',
    storageBucket: 'notes-d4f24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm30FNM2V6b9X_rzqG4yr2RSbIYxdIzQY',
    appId: '1:997695311497:ios:d51802c4cbd27a69850058',
    messagingSenderId: '997695311497',
    projectId: 'notes-d4f24',
    storageBucket: 'notes-d4f24.firebasestorage.app',
    iosBundleId: 'com.example.notesAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm30FNM2V6b9X_rzqG4yr2RSbIYxdIzQY',
    appId: '1:997695311497:ios:d51802c4cbd27a69850058',
    messagingSenderId: '997695311497',
    projectId: 'notes-d4f24',
    storageBucket: 'notes-d4f24.firebasestorage.app',
    iosBundleId: 'com.example.notesAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHkAOtSes9-9FEfY1mnB4R4VcYu2jAcEY',
    appId: '1:997695311497:web:5c47e17a938e5b02850058',
    messagingSenderId: '997695311497',
    projectId: 'notes-d4f24',
    authDomain: 'notes-d4f24.firebaseapp.com',
    storageBucket: 'notes-d4f24.firebasestorage.app',
    measurementId: 'G-0X7DSK9GKD',
  );
}
